export const AUTH = {
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGIN_CANCEL: "AUTH_LOGIN_CANCEL",
  AUTH_LOGIN_PROCESSING: "AUTH_LOGIN_PROCESSING"
};
