export const ROLE = {
  ROLE_GETALL: "ROLE_GETALL",
  ROLE_GETALL_SUCCESS: "ROLE_GETALL_SUCCESS",
  ROLE_GETALL_FAILURE: "ROLE_GETALL_FAILURE",

  ROLE_CHANGE_STATUS: "ROLE_CHANGE_STATUS",
  ROLE_CHANGE_STATUS_SUCCESS: "ROLE_CHANGE_STATUS_SUCCESS",
  ROLE_CHANGE_STATUS_FAILURE: "ROLE_CHANGE_STATUS_FAILURE",

  ROLE_DELETE: "ROLE_DELETE",
  ROLE_DELETE_SUCCESS: "ROLE_DELETE_SUCCESS",
  ROLE_DELETE_FAILURE: "ROLE_DELETE_FAILURE",
};