export const USER = {
    USER_GETALL: "USER_GETALL",
    USER_GETALL_SUCCESS: "USER_GETALL_SUCCESS",
    USER_GETALL_FAILURE: "USER_GETALL_FAILURE",

    USER_CHANGE_STATUS: "USER_CHANGE_STATUS",
    USER_CHANGE_STATUS_SUCCESS: "USER_CHANGE_STATUS_SUCCESS",
    USER_CHANGE_STATUS_FAILURE: "USER_CHANGE_STATUS_FAILURE",
  
    USER_DELETE: "USER_DELETE",
    USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
    USER_DELETE_FAILURE: "USER_DELETE_FAILURE",
  };